{% set name = "brukerapi" %}
{% set version = "0.1.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/brukerapi-{{ version }}.tar.gz
  sha256: d3dbff72b0ac68fac8427475b3310aa11fe06238d466a4b52ac64d857cc3d090

build:
  number: 0
  noarch: python
  entry_points:
    - bruker=brukerapi.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - pyyaml

test:
  imports:
    - brukerapi
  commands:
    - pip check
    - bruker --help
  requires:
    - pip

about:
  home: https://github.com/isi-nmr/brukerapi-python
  summary: Python package providing I/O interface for MR datasets in the Bruker proprietary data format
  license: MIT
  license_file: LICENSE
  doc_url: https://bruker-api.readthedocs.io/

extra:
  recipe-maintainers:
    - wtclarke
    - headmeister
    - tomas-psorn
