{% set name = "brukerapi" %}
{% set version = "0.1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brukerapi-{{ version }}.tar.gz
  sha256: 25b70f4af1088d39184719d5ea92694098488431612fe08f0b944045b3bef6cc

build:
  number: 0
  noarch: python
  entry_points:
    - bruker=brukerapi.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - numpy
    - python
    - pyyaml

test:
  imports:
    - brukerapi
  commands:
    - pip check
    - bruker --help
  requires:
    - pip

about:
  home: https://github.com/isi-nmr/brukerapi-python
  summary: Python package providing I/O interface for MR datasets in the Bruker proprietary data format
  license: MIT
  license_file: LICENSE
  doc_url: https://bruker-api.readthedocs.io/

extra:
  recipe-maintainers:
    - tomas-psorn
